mini-boardgame:
  wechat:
    auth-url: https://api.weixin.qq.com/sns/jscode2session
    app-id: ENC(rwJAuwpklOsOYUn+hQmpfzHPDTSPdAgWue+IIuqS+4Q=)
    app-secret: ENC(oqT9rGVThwro9EhVLw70lzDc9Phf81QtXAb61BezdhWtg5zYetDCM+fqrGZ6pG6O)