logging:
  level:
    xdean: DEBUG
server:
  port: 8081 # https port
  ssl:
    key-store: classpath:mini-boardgame.keystore.p12
    key-alias: mini-boardgame
    key-store-password: ENC(1dMghz7ibVQjt7nzopiT4bQLVb3xqCMK)
    key-store-type: PKCS12
  http:
    port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/
    username: mini-boardgame
    password: ENC(mGx6EfldKnWAtnW1Inuaybklce0prGqF)
    driver-class-name: com.mysql.jdbc.Driver
    schema:
    - classpath:security_schema.sql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
