logging:
  level:
    xdean: DEBUG
server:
  port: 8081
  ssl:
    key-store: classpath:mini-boardgame.keystore.p12
    key-alias: mini-boardgame
    key-store-password: ENC(1dMghz7ibVQjt7nzopiT4bQLVb3xqCMK)
    key-store-type: PKCS12
  http:
    port: 8080
  servlet:
    context-path: /mini-boardgame